/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OpenChatStudioWidget {
        /**
          * Allow the user to attach files to their messages.
          * @default false
         */
        "allowAttachments": boolean;
        /**
          * Allow the user to make the chat window full screen.
          * @default true
         */
        "allowFullScreen": boolean;
        /**
          * The base URL for the API.
          * @default "https://www.openchatstudio.com"
         */
        "apiBaseUrl"?: string;
        /**
          * The shape of the chat button. 'round' makes it circular, 'square' keeps it rectangular.
          * @default 'square'
         */
        "buttonShape": 'round' | 'square';
        /**
          * The text to display on the button.
         */
        "buttonText"?: string;
        /**
          * The ID of the chatbot to connect to.
         */
        "chatbotId": string;
        /**
          * Restrict dragging to a specific axis. Only applies when enableDragging is true.
          * @default 'both'
         */
        "dragAxis"?: 'both' | 'x' | 'y';
        /**
          * Enable dragging/moving the chat widget. When false (default), the widget position is fixed.
          * @default false
         */
        "enableDragging"?: boolean;
        /**
          * The text to place in the header.
         */
        "headerText": '';
        /**
          * URL of the icon to display on the button. If not provided, uses the default OCS logo.
         */
        "iconUrl"?: string;
        /**
          * Initial position of the widget. Can be a corner name or pixel coordinates. Corners: 'bottom-right', 'bottom-left', 'top-right', 'top-left' Coordinates: { x: number, y: number }
          * @default 'bottom-right'
         */
        "initialPosition"?: string | object;
        /**
          * The language code for the widget UI (e.g., 'en', 'es', 'fr'). Defaults to en
         */
        "language"?: string;
        /**
          * The message to display in the new chat confirmation dialog.
          * @default "Starting a new chat will clear your current conversation. Continue?"
         */
        "newChatConfirmationMessage"?: string;
        /**
          * Whether to persist session data to local storage to allow resuming previous conversations after page reload.
          * @default true
         */
        "persistentSession": boolean;
        /**
          * Minutes since the most recent message after which the session data in local storage will expire. Set this to `0` to never expire.
          * @default 60 * 24
         */
        "persistentSessionExpire": number;
        /**
          * The initial position of the chat widget on the screen.
          * @default 'right'
         */
        "position": 'left' | 'center' | 'right';
        /**
          * Custom persistence adapter for saving/loading widget position. Provide get() and set(pos) methods.
         */
        "positionPersistence"?: {
    get: () => { x: number; y: number } | null;
    set: (pos: { x: number; y: number }) => void;
  };
        /**
          * Safe margin from viewport edges in pixels. Can be a number or object with top/right/bottom/left.
          * @default 12
         */
        "safeMargin"?: number | object;
        /**
          * Distance in pixels from edge to trigger snap. Only applies when snapToEdges is true.
          * @default 32
         */
        "snapThreshold"?: number;
        /**
          * Automatically snap to nearest edge when drag ends within snapThreshold pixels.
          * @default true
         */
        "snapToEdges"?: boolean;
        /**
          * Array of starter questions that users can click to send (JSON array of strings)
         */
        "starterQuestions"?: string;
        "translationsUrl"?: string;
        /**
          * The text to display while the assistant is typing/preparing a response.
          * @default "Preparing response"
         */
        "typingIndicatorText"?: string;
        /**
          * Used to associate chat sessions with a specific user across multiple visits/sessions
         */
        "userId"?: string;
        /**
          * Display name for the user.
         */
        "userName"?: string;
        /**
          * Whether the chat widget is visible on load.
          * @default false
         */
        "visible": boolean;
        /**
          * Welcome messages to display above starter questions (JSON array of strings)
         */
        "welcomeMessages"?: string;
        /**
          * Override the z-index of the chat widget.
         */
        "zIndexOverride"?: number;
    }
}
export interface OpenChatStudioWidgetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOpenChatStudioWidgetElement;
}
declare global {
    interface HTMLOpenChatStudioWidgetElementEventMap {
        "positionChange": { x: number; y: number };
    }
    interface HTMLOpenChatStudioWidgetElement extends Components.OpenChatStudioWidget, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOpenChatStudioWidgetElementEventMap>(type: K, listener: (this: HTMLOpenChatStudioWidgetElement, ev: OpenChatStudioWidgetCustomEvent<HTMLOpenChatStudioWidgetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOpenChatStudioWidgetElementEventMap>(type: K, listener: (this: HTMLOpenChatStudioWidgetElement, ev: OpenChatStudioWidgetCustomEvent<HTMLOpenChatStudioWidgetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOpenChatStudioWidgetElement: {
        prototype: HTMLOpenChatStudioWidgetElement;
        new (): HTMLOpenChatStudioWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "open-chat-studio-widget": HTMLOpenChatStudioWidgetElement;
    }
}
declare namespace LocalJSX {
    interface OpenChatStudioWidget {
        /**
          * Allow the user to attach files to their messages.
          * @default false
         */
        "allowAttachments"?: boolean;
        /**
          * Allow the user to make the chat window full screen.
          * @default true
         */
        "allowFullScreen"?: boolean;
        /**
          * The base URL for the API.
          * @default "https://www.openchatstudio.com"
         */
        "apiBaseUrl"?: string;
        /**
          * The shape of the chat button. 'round' makes it circular, 'square' keeps it rectangular.
          * @default 'square'
         */
        "buttonShape"?: 'round' | 'square';
        /**
          * The text to display on the button.
         */
        "buttonText"?: string;
        /**
          * The ID of the chatbot to connect to.
         */
        "chatbotId": string;
        /**
          * Restrict dragging to a specific axis. Only applies when enableDragging is true.
          * @default 'both'
         */
        "dragAxis"?: 'both' | 'x' | 'y';
        /**
          * Enable dragging/moving the chat widget. When false (default), the widget position is fixed.
          * @default false
         */
        "enableDragging"?: boolean;
        /**
          * The text to place in the header.
         */
        "headerText"?: '';
        /**
          * URL of the icon to display on the button. If not provided, uses the default OCS logo.
         */
        "iconUrl"?: string;
        /**
          * Initial position of the widget. Can be a corner name or pixel coordinates. Corners: 'bottom-right', 'bottom-left', 'top-right', 'top-left' Coordinates: { x: number, y: number }
          * @default 'bottom-right'
         */
        "initialPosition"?: string | object;
        /**
          * The language code for the widget UI (e.g., 'en', 'es', 'fr'). Defaults to en
         */
        "language"?: string;
        /**
          * The message to display in the new chat confirmation dialog.
          * @default "Starting a new chat will clear your current conversation. Continue?"
         */
        "newChatConfirmationMessage"?: string;
        /**
          * Event fired when widget position changes. Emits { x, y } coordinates.
         */
        "onPositionChange"?: (event: OpenChatStudioWidgetCustomEvent<{ x: number; y: number }>) => void;
        /**
          * Whether to persist session data to local storage to allow resuming previous conversations after page reload.
          * @default true
         */
        "persistentSession"?: boolean;
        /**
          * Minutes since the most recent message after which the session data in local storage will expire. Set this to `0` to never expire.
          * @default 60 * 24
         */
        "persistentSessionExpire"?: number;
        /**
          * The initial position of the chat widget on the screen.
          * @default 'right'
         */
        "position"?: 'left' | 'center' | 'right';
        /**
          * Custom persistence adapter for saving/loading widget position. Provide get() and set(pos) methods.
         */
        "positionPersistence"?: {
    get: () => { x: number; y: number } | null;
    set: (pos: { x: number; y: number }) => void;
  };
        /**
          * Safe margin from viewport edges in pixels. Can be a number or object with top/right/bottom/left.
          * @default 12
         */
        "safeMargin"?: number | object;
        /**
          * Distance in pixels from edge to trigger snap. Only applies when snapToEdges is true.
          * @default 32
         */
        "snapThreshold"?: number;
        /**
          * Automatically snap to nearest edge when drag ends within snapThreshold pixels.
          * @default true
         */
        "snapToEdges"?: boolean;
        /**
          * Array of starter questions that users can click to send (JSON array of strings)
         */
        "starterQuestions"?: string;
        "translationsUrl"?: string;
        /**
          * The text to display while the assistant is typing/preparing a response.
          * @default "Preparing response"
         */
        "typingIndicatorText"?: string;
        /**
          * Used to associate chat sessions with a specific user across multiple visits/sessions
         */
        "userId"?: string;
        /**
          * Display name for the user.
         */
        "userName"?: string;
        /**
          * Whether the chat widget is visible on load.
          * @default false
         */
        "visible"?: boolean;
        /**
          * Welcome messages to display above starter questions (JSON array of strings)
         */
        "welcomeMessages"?: string;
        /**
          * Override the z-index of the chat widget.
         */
        "zIndexOverride"?: number;
    }
    interface IntrinsicElements {
        "open-chat-studio-widget": OpenChatStudioWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "open-chat-studio-widget": LocalJSX.OpenChatStudioWidget & JSXBase.HTMLAttributes<HTMLOpenChatStudioWidgetElement>;
        }
    }
}
